language: node_js
cache: yarn
notifications:
  email: false
node_js:
    - node
install:
  - yarn install --ignore-engines
scripts:
  - yarn build
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
branches:
  only:
    - master
